name: flutter_common
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # 本地push通知
  flutter_local_notifications: ^3.0.1+2
  rxdart: ^0.24.1
  # sql
  sqflite: ^1.3.2+1
  # 刷脸认证/指纹认证
  local_auth: ^0.6.3+4 
  # 密码验证
  passcode_screen: ^1.2.2+1 

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_common
        pluginClass: FlutterCommonPlugin
      ios:
        pluginClass: FlutterCommonPlugin

    assets:
      - images/warnning.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
